// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllLoginAccounts() {
  return window['go']['app']['App']['ClearAllLoginAccounts']();
}

export function ClearSharedLoginSession() {
  return window['go']['app']['App']['ClearSharedLoginSession']();
}

export function CreateScrapyItem(arg1) {
  return window['go']['app']['App']['CreateScrapyItem'](arg1);
}

export function DeleteLoginAccount(arg1) {
  return window['go']['app']['App']['DeleteLoginAccount'](arg1);
}

export function DeleteScrapyItem(arg1) {
  return window['go']['app']['App']['DeleteScrapyItem'](arg1);
}

export function DoneTask(arg1) {
  return window['go']['app']['App']['DoneTask'](arg1);
}

export function GetC2CItemNameBySku(arg1) {
  return window['go']['app']['App']['GetC2CItemNameBySku'](arg1);
}

export function GetLoginKeyAndUrl() {
  return window['go']['app']['App']['GetLoginKeyAndUrl']();
}

export function GetMarketRuntimeConfig(arg1) {
  return window['go']['app']['App']['GetMarketRuntimeConfig'](arg1);
}

export function GetMonitorConfig() {
  return window['go']['app']['App']['GetMonitorConfig']();
}

export function GetNowRunTaskId() {
  return window['go']['app']['App']['GetNowRunTaskId']();
}

export function GetRunningTaskIds() {
  return window['go']['app']['App']['GetRunningTaskIds']();
}

export function GetSharedLoginSession() {
  return window['go']['app']['App']['GetSharedLoginSession']();
}

export function HasRunningTasks() {
  return window['go']['app']['App']['HasRunningTasks']();
}

export function Initialize() {
  return window['go']['app']['App']['Initialize']();
}

export function IsAnyTaskRunningWithAccount(arg1) {
  return window['go']['app']['App']['IsAnyTaskRunningWithAccount'](arg1);
}

export function ListC2CItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['ListC2CItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ListC2CItemDetailBySku(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['ListC2CItemDetailBySku'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListLoginAccounts() {
  return window['go']['app']['App']['ListLoginAccounts']();
}

export function ListMonitorRuleHits(arg1) {
  return window['go']['app']['App']['ListMonitorRuleHits'](arg1);
}

export function ReadAllScrapyItems() {
  return window['go']['app']['App']['ReadAllScrapyItems']();
}

export function ResolveLoginCookie(arg1) {
  return window['go']['app']['App']['ResolveLoginCookie'](arg1);
}

export function SaveMonitorConfig(arg1) {
  return window['go']['app']['App']['SaveMonitorConfig'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['app']['App']['StartTask'](arg1, arg2);
}

export function SubscribeEvents(arg1) {
  return window['go']['app']['App']['SubscribeEvents'](arg1);
}

export function UpdateScrapyTaskConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateScrapyTaskConfig'](arg1, arg2, arg3);
}

export function VerifyLogin(arg1) {
  return window['go']['app']['App']['VerifyLogin'](arg1);
}
