// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScrapyItem(arg1) {
  return window['go']['app']['App']['CreateScrapyItem'](arg1);
}

export function DeleteScrapyItem(arg1) {
  return window['go']['app']['App']['DeleteScrapyItem'](arg1);
}

export function DoneTask(arg1) {
  return window['go']['app']['App']['DoneTask'](arg1);
}

export function GetC2CItemNameBySku(arg1) {
  return window['go']['app']['App']['GetC2CItemNameBySku'](arg1);
}

export function GetLoginKeyAndUrl() {
  return window['go']['app']['App']['GetLoginKeyAndUrl']();
}

export function GetMarketRuntimeConfig(arg1) {
  return window['go']['app']['App']['GetMarketRuntimeConfig'](arg1);
}

export function GetMonitorConfig() {
  return window['go']['app']['App']['GetMonitorConfig']();
}

export function GetNowRunTaskId() {
  return window['go']['app']['App']['GetNowRunTaskId']();
}

export function GetRunningTaskIds() {
  return window['go']['app']['App']['GetRunningTaskIds']();
}

export function ListC2CItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['ListC2CItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ListC2CItemDetailBySku(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['ListC2CItemDetailBySku'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReadAllScrapyItems() {
  return window['go']['app']['App']['ReadAllScrapyItems']();
}

export function SaveMonitorConfig(arg1) {
  return window['go']['app']['App']['SaveMonitorConfig'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['app']['App']['StartTask'](arg1, arg2);
}

export function VerifyLogin(arg1) {
  return window['go']['app']['App']['VerifyLogin'](arg1);
}
